import { CreatorRankingUpDownType } from '@somesay/shared';

export const MOCK_RANKING_CREATORS: CreatorRankingUpDownType[] = [
  {
    ranking: 1,
    rankChange: 'up',
    rankChangeDiff: 2,
    profileImageUrl: '/mocks/images/creator-risabae.png',
    nickname: 'RISABAE',
    subscriberCount: 130,
    ageGroup: 20,
    skinType: '건성',
    trustScore: 100,
    creatorId: 1,
  },
  {
    ranking: 2,
    rankChange: 'same',
    rankChangeDiff: 0,
    profileImageUrl: '/mocks/images/creator-kimjumrye.png',
    nickname: '김점례',
    subscriberCount: 30,
    ageGroup: 20,
    skinType: '건성',
    trustScore: 95,
    creatorId: 2,
  },
  {
    ranking: 3,
    rankChange: 'down',
    rankChangeDiff: 1,
    profileImageUrl: '/mocks/images/creator-otter.png',
    nickname: '뷰티수달',
    subscriberCount: 12,
    ageGroup: 30,
    skinType: '복합성',
    trustScore: 87,
    creatorId: 3,
  },
  {
    ranking: 4,
    rankChange: 'up',
    rankChangeDiff: 3,
    profileImageUrl: '/mocks/images/creator-olive.png',
    nickname: '올리브언니',
    subscriberCount: 45,
    ageGroup: 20,
    skinType: '지성',
    trustScore: 82,
    creatorId: 4,
  },
  {
    ranking: 5,
    rankChange: 'down',
    rankChangeDiff: 2,
    profileImageUrl: '/mocks/images/creator-doctor.png',
    nickname: '닥터스킨',
    subscriberCount: 61,
    ageGroup: 30,
    skinType: '중성',
    trustScore: 79,
    creatorId: 5,
  },
];
