import { CreatorRankingUpDownType } from '@somesay/shared';

export const MOCK_RANKING_CREATORS: CreatorRankingUpDownType[] = [
  {
    ranking: 1,
    rankChange: 2,
    rankChangeDiff: 'up',
    profileImageUrl: '/mocks/images/creator-risabae.png',
    nickname: 'RISABAE',
    youtubeLink: '',
    subscriberNum: 130,
    ageGroup: 20,
    skinTypes: ['건성'],
    trustScore: 100,
    creatorId: 1,
  },
  {
    ranking: 2,
    rankChange: 0,
    rankChangeDiff: 'same',
    profileImageUrl: '/mocks/images/creator-kimjumrye.png',
    nickname: '김점례',
    youtubeLink: '',
    subscriberNum: 30,
    ageGroup: 20,
    skinTypes: ['건성'],
    trustScore: 95,
    creatorId: 2,
  },
  {
    ranking: 3,
    rankChange: 1,
    rankChangeDiff: 'down',
    profileImageUrl: '/mocks/images/creator-otter.png',
    nickname: '뷰티수달',
    youtubeLink: '',
    subscriberNum: 12,
    ageGroup: 30,
    skinTypes: ['복합성'],
    trustScore: 87,
    creatorId: 3,
  },
  {
    ranking: 4,
    rankChange: 3,
    rankChangeDiff: 'up',
    profileImageUrl: '/mocks/images/creator-olive.png',
    nickname: '올리브언니',
    youtubeLink: '',
    subscriberNum: 45,
    ageGroup: 20,
    skinTypes: ['지성'],
    trustScore: 82,
    creatorId: 4,
  },
  {
    ranking: 5,
    rankChange: 2,
    rankChangeDiff: 'down',
    profileImageUrl: '/mocks/images/creator-doctor.png',
    nickname: '닥터스킨',
    youtubeLink: '',
    subscriberNum: 61,
    ageGroup: 30,
    skinTypes: ['중성'],
    trustScore: 79,
    creatorId: 5,
  },
];
