export const MOCK_RANKING_CREATORS = [
  {
    rank: 1,
    rankChange: 'up',
    rankChangeDiff: 2,
    profileImageUrl: '/mocks/images/creator-risabae.png',
    name: 'RISABAE',
    subscriberCount: 130,
    ageGroup: 20,
    skinType: '건성',
    trustScore: 100,
  },
  {
    rank: 2,
    rankChange: 'same',
    rankChangeDiff: 0,
    profileImageUrl: '/mocks/images/creator-kimjumrye.png',
    name: '김점례',
    subscriberCount: 30,
    ageGroup: 20,
    skinType: '건성',
    trustScore: 95,
  },
  {
    rank: 3,
    rankChange: 'down',
    rankChangeDiff: 1,
    profileImageUrl: '/mocks/images/creator-otter.png',
    name: '뷰티수달',
    subscriberCount: 12,
    ageGroup: 30,
    skinType: '복합성',
    trustScore: 87,
  },
  {
    rank: 4,
    rankChange: 'up',
    rankChangeDiff: 3,
    profileImageUrl: '/mocks/images/creator-olive.png',
    name: '올리브언니',
    subscriberCount: 45,
    ageGroup: 20,
    skinType: '지성',
    trustScore: 82,
  },
  {
    rank: 5,
    rankChange: 'down',
    rankChangeDiff: 2,
    profileImageUrl: '/mocks/images/creator-doctor.png',
    name: '닥터스킨',
    subscriberCount: 61,
    ageGroup: 30,
    skinType: '중성',
    trustScore: 79,
  },
];
