import mockProductImage from '@/assets/mock_product_img.png';
import type { SelectableProduct } from './types/productSelection.types';

export const MOCK_PRODUCT_CATALOG: SelectableProduct[] = [
  {
    productId: 1,
    productImgUrl: mockProductImage,
    brandName: '설화수',
    productName: '자음생 워터 패드',
    categoryId: 1,
  },
  {
    productId: 2,
    productImgUrl: mockProductImage,
    brandName: '스킨푸드',
    productName: '캐롯 카로틴 카밍 워터 패드',
    categoryId: 1,
  },
  {
    productId: 3,
    productImgUrl: mockProductImage,
    brandName: '이니스프리',
    productName: '그린티 씨드 히알루론산 세럼',
    categoryId: 1,
  },
  {
    productId: 4,
    productImgUrl: mockProductImage,
    brandName: '라로슈포제',
    productName: '시카플라스트 밤 B5+',
    categoryId: 1,
  },
  {
    productId: 5,
    productImgUrl: mockProductImage,
    brandName: '아비브',
    productName: '어성초 카밍 토너 스킨부스터',
    categoryId: 1,
  },
  {
    productId: 6,
    productImgUrl: mockProductImage,
    brandName: '이니스프리',
    productName: '화산송이 바하 모공 클렌징폼',
    categoryId: 2,
  },
  {
    productId: 7,
    productImgUrl: mockProductImage,
    brandName: '아비브',
    productName: '약산성 피에이치 시트 마스크',
    categoryId: 3,
  },
  {
    productId: 8,
    productImgUrl: mockProductImage,
    brandName: '메디힐',
    productName: '티트리 에센셜 마스크',
    categoryId: 3,
  },
  {
    productId: 9,
    productImgUrl: mockProductImage,
    brandName: '라운드랩',
    productName: '자작나무 수분 선크림',
    categoryId: 4,
  },
  {
    productId: 10,
    productImgUrl: mockProductImage,
    brandName: '헤라',
    productName: '블랙 쿠션 파운데이션',
    categoryId: 5,
  },
  {
    productId: 11,
    productImgUrl: mockProductImage,
    brandName: '정샘물',
    productName: '에센셜 스킨 누더 쿠션',
    categoryId: 5,
  },
  {
    productId: 12,
    productImgUrl: mockProductImage,
    brandName: '바이오더마',
    productName: '센시비오 에이치투오',
    categoryId: 2,
  },
  {
    productId: 13,
    productImgUrl: mockProductImage,
    brandName: '닥터자르트',
    productName: '세라마이딘 크림',
    categoryId: 1,
  },
  {
    productId: 14,
    productImgUrl: mockProductImage,
    brandName: '코스알엑스',
    productName: '달팽이 뮤신 파워 에센스',
    categoryId: 1,
  },
  {
    productId: 15,
    productImgUrl: mockProductImage,
    brandName: '토리든',
    productName: '다이브인 저분자 히알루론산 세럼',
    categoryId: 1,
  },
  {
    productId: 16,
    productImgUrl: mockProductImage,
    brandName: '에스트라',
    productName: '아토베리어365 크림',
    categoryId: 1,
  },
];
